model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val_acc_epoch" # name of the logged metric which determines when model is improving
  mode: "max" # can be "max" or "min"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  verbose: False
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: False

upload_code_as_artifact:
  _target_: src.callbacks.wandb_callbacks.UploadCodeAsArtifact
  code_dir: ${work_dir}/src

# log_image_predictions:
#   _target_: src.callbacks.wandb_callbacks.LogImagePredictions
#   num_samples: 8


# early_stopping:
#   _target_: pytorch_lightning.callbacks.EarlyStopping
#   monitor: "val_acc_epoch" # name of the logged metric which determines when model is improving
#   mode: "max" # can be "max" or "min"
#   patience: 100 # how many epochs of not improving until training stops
#   min_delta: 0 # minimum change in the monitored metric needed to qualify as an improvement
